const express = require("express");
const fs = require("fs");
const path = require("path");
const dotenv = require("dotenv");
const NodeCache = require("node-cache");
const { getFilmAffinityRating } = require("./services/filmaffinity");
dotenv.config();

const app = express();

// In-memory cache TTL (defaults to 1 day)
const cache = new NodeCache({
  stdTTL: parseInt(process.env.CACHE_TTL || "86400"),
  checkperiod: 120,
});

const PORT = process.env.PORT || 8085;
const CACHE_FILE = path.join(__dirname, "../data/ratings.json");

// Request logging middleware
app.use((req, res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.url}`);
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  next();
});

// Main endpoint
app.get("/rating", async (req, res) => {
  const { title } = req.query;
  if (!title)
    return res.status(400).json({ error: 'Missing "title" query parameter' });

  const cacheKey = title.toLowerCase();

  // 1. Check in-memory cache first
  if (cache.has(cacheKey)) {
    console.log(`In-memory cache hit: ${title}`);
    return res.json(cache.get(cacheKey));
  }

  // 2. Then check the local cache file (JSON generated by cron)
  if (fs.existsSync(CACHE_FILE)) {
    try {
      const jsonData = JSON.parse(fs.readFileSync(CACHE_FILE, "utf-8"));
      if (jsonData[cacheKey]) {
        console.log(`File cache hit: ${title}`);
        cache.set(cacheKey, jsonData[cacheKey]); // Keep it in RAM too
        return res.json(jsonData[cacheKey]);
      }
    } catch (err) {
      console.error("Error reading local cache:", err.message);
    }
  }

  // 3. If it is not cached, scrape it directly as a fallback
  console.log(`Fetching FilmAffinity rating for: ${title}`);
  try {
    const data = await getFilmAffinityRating(title);

    if (!data || !data.rating) {
      console.warn(`No result found for "${title}"`);
      return res.status(404).json({ error: "No result found" });
    }

    // Store in memory cache
    cache.set(cacheKey, data);

    // Update local JSON cache as well
    let currentCache = {};
    if (fs.existsSync(CACHE_FILE)) {
      try {
        currentCache = JSON.parse(fs.readFileSync(CACHE_FILE, "utf-8"));
      } catch {}
    }
    currentCache[cacheKey] = data;
    fs.mkdirSync(path.dirname(CACHE_FILE), { recursive: true });
    fs.writeFileSync(CACHE_FILE, JSON.stringify(currentCache, null, 2), "utf-8");

    console.log(`Stored in cache: ${title} (${data.rating})`);
    res.json(data);
  } catch (err) {
    console.error("Error fetching rating:", err.message);
    res.status(500).json({ error: "Internal server error" });
  }
});

// Health endpoint
app.get("/health", (req, res) =>
  res.json({ status: "ok", cacheTTL: cache.options.stdTTL })
);

// Server startup
app.listen(PORT, () => {
  console.log(`FilmAffinity Scores API running on port ${PORT}`);
  console.log(`Cache TTL: ${cache.options.stdTTL}s`);
});
